// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs3rNzuqhQSG2jqe1JYtvGRfLC7hMhEp8',
    appId: '1:890613517885:web:db43cfb76eaa15078fe454',
    messagingSenderId: '890613517885',
    projectId: 'chat-app-bloc-cc3c8',
    authDomain: 'chat-app-bloc-cc3c8.firebaseapp.com',
    storageBucket: 'chat-app-bloc-cc3c8.appspot.com',
    measurementId: 'G-JYQQNJM3NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9sgp-M4MH-mgEhzrXrnkrXRL4KIcru4c',
    appId: '1:890613517885:android:9fd656e656cf34258fe454',
    messagingSenderId: '890613517885',
    projectId: 'chat-app-bloc-cc3c8',
    storageBucket: 'chat-app-bloc-cc3c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnUPrhGScN5_JhXvkKBMJj1tmfWdMgtt4',
    appId: '1:890613517885:ios:13beb25368197e7d8fe454',
    messagingSenderId: '890613517885',
    projectId: 'chat-app-bloc-cc3c8',
    storageBucket: 'chat-app-bloc-cc3c8.appspot.com',
    iosClientId: '890613517885-8gasauffblupbbbiqa0odvfj80cpg25q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnUPrhGScN5_JhXvkKBMJj1tmfWdMgtt4',
    appId: '1:890613517885:ios:13beb25368197e7d8fe454',
    messagingSenderId: '890613517885',
    projectId: 'chat-app-bloc-cc3c8',
    storageBucket: 'chat-app-bloc-cc3c8.appspot.com',
    iosClientId: '890613517885-8gasauffblupbbbiqa0odvfj80cpg25q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppBloc',
  );
}
